
var clickSnd = new Audio("audio/click.mp3");
var winSnd = new Audio("audio/win.mp3");

var JSONBingo = {"squares": [

        {"square": "<i>Bastis Wohnheim Stories</i> <ion-icon name='musical-notes-outline'></ion-icon>"},
        {"square": "<i>Dr. Fahrmaus</i><br><ion-icon name='musical-notes-outline'></ion-icon>"},
        {"square": "<i>zu weeenig</i>"},
        {"square": "<i>In Neuss?</i><br><ion-icon name='thunderstorm-outline'></ion-icon>"},
        {"square": "<i>Ich habe in meinem Leben schon viele...</i>"},
        {"square": "'Ich sehe reich aus'"},
        {"square": "Sahne abkeulen"},
        {"square": "Die Frau mit den roten Augen"},
        {"square": "*Ostdeutsch*"},
        {"square": "Das sind soundso viel DM"},
        {"square": "m/w/d"},
        {"square": "Igendwas mit Obdachlosen"},
        {"square": "'Ich in der Klausur'"},
        {"square": "'Ich war Chefredak-teur'"},
        {"square": "Etwas ist unangenehm"},
        {"square": "Basti wird reich genannt"},
        {"square": "Basti sagt selbst er ist reich"},
        {"square": "'Internetstar @anredo'"},
        {"square": "<i>Raus mit die Viecher</i>"},
        {"square": "<i>M&ouml;chten Sie ein Hei&szlig;-getr&auml;nk</i>"},
        {"square": "'LG Susanne'"},
        {"square": "'Sch&ouml;ne Damenfrisur'"},
        {"square": "Basti lacht laut"},
        {"square": "Kot-Geschichte"},
        {"square": "K&ouml;rperpflege-Studium"},
        {"square": "Helena F&uuml;rst"},
        {"square": "Rollenspiel"},
        {"square": "Jemand schreit"},
        {"square": "'Roundy Founky Seventeen'"},
        {"square": "'Manfredo'"},
        {"square": "702 Euro 10"},
        {"square": "'K&ouml;nnen wir das nachspielen?'"},
        {"square": "Mayonnaise Wohnung"},
        {"square": ""},
        {"square": ""},
        {"square": ""},
        {"square": ""},
        {"square": ""},
        {"square": ""},
        {"square": ""},
        {"square": ""},
        {"square": "Podcast soll beendet werden"},

    ]
};
